# Generated by Django 3.1.1 on 2021-08-12 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_num', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('transaction_status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CLOSE', 'CLOSE')], default='PENDING', max_length=14)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.branchmaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.companyledgermaster')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.departmentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.IntegerField()),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('METRE', 'METRE')], max_length=15)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.colormaster')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('net_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('METRE', 'METRE')], max_length=15)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.articlemaster')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.colormaster')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.companyledgermaster')),
                ('lineitem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.transactionlineitem')),
            ],
        ),
    ]
