# Generated by Django 3.1.1 on 2021-08-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20210812_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_num',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
