# Generated by Django 3.1.1 on 2021-08-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20210812_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionlineitem',
            unique_together={('transaction', 'article', 'colour')},
        ),
    ]
